# This file was generated by Rigel.
############################################################################

# Use an intermediate stage to clone external repositories without
# compromising the security of any private SSH key.
FROM ros:noetic as intermediate

RUN apt clean && apt update && apt install -y \
    git \
    python3-rosinstall \
    python3-vcstool \
    ssh

RUN mkdir -p /root/.ssh/



# Ensure hosts are accepted.
RUN touch /root/.ssh/known_hosts

RUN mkdir -p /ros_workspace/src



# Clone repositories.
RUN cd /ros_workspace \ 
    && /bin/bash -c "source /opt/ros/noetic/setup.bash \
    " && echo

############################################################################

FROM ros:noetic

# Install dependencies.
RUN sudo apt clean && sudo apt update && sudo apt install -y \
    xfce4-terminal \
    ros-noetic-ros-numpy \
    python3-pip \
    git-all \
    ssh

# Execute additional commands.
RUN pip3 install rospy_message_converter
RUN pip3 install opencv-contrib-python==4.6.0.66
RUN pip3 install JSON-minify
RUN pip3 install jinja2
RUN pip3 install alphashape
RUN pip3 install descartes
RUN pip3 install colorama
RUN pip3 install graphviz
RUN pip3 install pandas
RUN pip3 install pynput
RUN pip3 install scipy
RUN pip3 install scipy
RUN pip3 install networkx
RUN pip3 install prettytable
RUN pip3 install readchar
RUN pip3 install urdf-parser-py
RUN pip3 install SQLAlchemy
RUN pip3 install open3d
RUN mkdir -p home/ros_workspace/src
RUN cd home/ros_workspace/src
RUN git clone https://github.com/miguelriemoliveira/rviz


# Create default user 'rigeluser'.
ARG USERNAME=rigeluser
RUN groupadd $USERNAME
RUN useradd -ms /bin/bash -g $USERNAME $USERNAME
RUN sh -c 'echo "$USERNAME ALL=(root) NOPASSWD:ALL" >> /etc/sudoers'
RUN sh -c 'sudo chown -R rigeluser:rigeluser /home/rigeluser'
USER $USERNAME

# Create ROS workspace folder
RUN mkdir -p /home/rigeluser/ros_workspace/src

# Copy this repository into the ROS workspace.
COPY . /home/rigeluser/ros_workspace/src/rigel_local_packages

# Copy bringup script.
COPY dockerfile_entrypoint.sh /home/rigeluser/robot-entrypoint.sh

# Compile ROS workspace.
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash \ 
    && cd /home/rigeluser/ros_workspace \
    
    && sudo rosdep fix-permissions \
    && rosdep update \
    && rosdep install --rosdistro noetic --from-paths src --ignore-src -r -y \
    && catkin_make "
    

# Give permissions to user
RUN sh -c 'sudo chmod +x /home/rigeluser/robot-entrypoint.sh'
RUN sh -c 'sudo chown rigeluser:rigeluser /home/rigeluser/robot-entrypoint.sh'

# Launch ROS application.
ENTRYPOINT [ "/home/rigeluser/robot-entrypoint.sh" ]