#!/bin/bash

# This file was generated by Rigel.

cd ~/ros_workspace/
source /opt/ros/noetic/setup.bash
source ./devel/setup.bash
if [[ -f "/usr/share/$GAZEBO_VERSION/setup.sh" ]]; then source /usr/share/$GAZEBO_VERSION/setup.sh; fi
export GAZEBO_RESOURCE_PATH=$GAZEBO_RESOURCE_PATH/usr/share/gazebo-11:
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH/usr/share/gazebo-11/meshes:
export WORKSPACE_INSTALL="home/rigeluser/ros_workspace/devel"
export ATOM_DATASETS="$HOME/ros_workspace/src/atom/ci_datasets/"
source $WORKSPACE_INSTALL/setup.bash
printenv

exec "${@:1}"