# This file was generated by Rigel.
############################################################################

# Use an intermediate stage to clone external repositories without
# compromising the security of any private SSH key.
FROM ros:noetic as intermediate

RUN apt clean && apt update && apt install -y \
    git \
    python3-rosinstall \
    python3-vcstool \
    ssh

RUN mkdir -p /root/.ssh/



# Ensure hosts are accepted.
RUN touch /root/.ssh/known_hosts

RUN mkdir -p /ros_workspace/src



# Clone repositories.
RUN cd /ros_workspace \ 
    && /bin/bash -c "source /opt/ros/noetic/setup.bash \
    " && echo

############################################################################

FROM ros:noetic

# Install dependencies.
RUN sudo apt clean && sudo apt update && sudo apt install -y \
    xfce4-terminal \
    ros-noetic-ros-numpy \
    python3-pip \
    git-all \
    qtbase5-dev \
    qtdeclarative5-dev \
    ssh

# Execute additional commands.
RUN pip install rospy_message_converter
RUN pip install opencv-contrib-python==4.6.0.66
RUN pip install JSON-minify
RUN pip install jinja2
RUN pip install alphashape
RUN pip install descartes
RUN pip install colorama
RUN pip install graphviz
RUN pip install pandas
RUN pip install pynput
RUN pip install scipy
RUN pip install scipy
RUN pip install networkx
RUN pip install prettytable
RUN pip install readchar
RUN pip install urdf-parser-py
RUN pip install SQLAlchemy
RUN pip install open3d
RUN mkdir -p home/rigeluser/ros_workspace/src
RUN cd home/rigeluser/ros_workspace/src
RUN git clone https://github.com/miguelriemoliveira/rviz


# Create default user 'rigeluser'.
ARG USERNAME=rigeluser
RUN groupadd $USERNAME
RUN useradd -ms /bin/bash -g $USERNAME $USERNAME
RUN sh -c 'echo "$USERNAME ALL=(root) NOPASSWD:ALL" >> /etc/sudoers'
RUN sh -c 'sudo chown -R rigeluser:rigeluser /home/rigeluser'
USER $USERNAME

# Create ROS workspace folder
RUN mkdir -p /home/rigeluser/ros_workspace/src

# Copy this repository into the ROS workspace.
COPY . /home/rigeluser/ros_workspace/src/rigel_local_packages

# Copy bringup script.
COPY dockerfile_entrypoint.sh /home/rigeluser/robot-entrypoint.sh

# Compile ROS workspace.
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash \ 
    && cd /home/rigeluser/ros_workspace \
    
    && sudo rosdep fix-permissions \
    && rosdep update \
    && rosdep install --rosdistro noetic --from-paths src --ignore-src -r -y \
    && catkin_make "
    

# Give permissions to user
RUN sh -c 'sudo chmod +x /home/rigeluser/robot-entrypoint.sh'
RUN sh -c 'sudo chown rigeluser:rigeluser /home/rigeluser/robot-entrypoint.sh'

# Launch ROS application.
ENTRYPOINT [ "/home/rigeluser/robot-entrypoint.sh" ]