name: CI

on: workflow_dispatch
  
jobs:
  run_atom_with_rigel:
    name: Testing ATOM with Rigel

    runs-on: ubuntu-20.04

    steps:
      
      - uses: actions/checkout@v3

      - name: Install Rigel and clone ATOM repo
        run: sudo apt update && cd ~/ && pip install git+https://github.com/rigel-ros/rigel@develop && cd ~/ && git clone --branch updated_atom https://github.com/Kazadhum/atom