name: rrbot_calib_four_noise_pairs

on: workflow_dispatch
  
jobs:
  test_calibration_evaluation:
    name: Testing Calibration and Evaluation

    runs-on: ubuntu-20.04

    steps:
      
      - uses: actions/checkout@v3

      - name: Install Rigel and clone ATOM repo
        run: sudo apt update && cd ~/ && pip install git+https://github.com/rigel-ros/rigel@develop && cd ~/ && git clone --branch updated_atom https://github.com/Kazadhum/atom

      - name: Fix OpenSSL
        run: sudo apt-get install -y python3-pip && sudo dpkg -r --force-depends python3-openssl python3-cryptography && sudo pip3 install pyopenssl cryptography && sudo apt-get install -y --fix-missing python3-openssl python3-cryptography

      - name: Install my File Introspection Plugin
        run: sudo apt install python3-pip && pip install git+https://github.com/Kazadhum/file_intro_plugin@flow

      - name: Test rrbot calibration and evaluation
        run: cd ~/atom/ && export DISPLAY=:99 && rigel run sequence test_rrbot_calibration_four_noise_pairs && ls
        env:
          DISPLAY: :99